requirements.txt
NerfAcc is currently being actively developed so there might be changes of API in the future. Anchor the version of it would be nice.
A side suggestion is maybe also add this for other dependences?
=> Anchor the version of nerfacc

CHANGELOG.md, DOCUMENTATION.md, configs/prolificdreamer.yaml, threestudio/data/uncond.py, threestudio/models/guidance/deep_floyd_guidance.py, threestudio/models/guidance/stable_diffusion_guidance.py, threestudio/models/guidance/stable_diffusion_vsd_guidance.py, threestudio/models/prompt_processors/base.py, threestudio/systems/dreamfusion.py, threestudio/systems/fantasia3d.py, threestudio/systems/imagedreamfusion.py, threestudio/systems/latentnerf.py, threestudio/systems/magic3d.py, threestudio/systems/prolificdreamer.py, threestudio/systems/sjc.py, threestudio/utils/ops.py
Changes:
- Prompt processors now return an instance of `PromptProcessorOutput`, which contains text embeddings, view-dependent text embeddings, direction configs, and a function to get text embeddings from camera settings. With this change, we can more easily implement VSD and Perp-Neg.
- `view_dependent_prompting` is now an option for guidance, not prompt processors.
- The returned dict of guidance now contains several items with keys starting with `loss_`. These items will be treated as loss terms, multiplied with the corresponding `lambda_`, and added to the final loss. With this change, we can easily adapt VSD to other systems, simply changing the guidance and loss lambdas in the configuration file.
- The LoRA of ProlificDreamer takes view-independent text embeddings instead of …
=> Refactor prompt processor

configs/zero123.yaml, configs/zero123_claforte.yaml, configs/zero123_finitediff.yaml, launch.py, threestudio/models/renderers/nerf_volume_renderer.py, threestudio/utils/config.py
- remove redundant config saving in `launch.py`
- change `lambda_normal_smooth` and `lambda_3d_normal_smooth` to `return_comp_normal` and `return_normal_perturb` in `nerf-volume-renderer`
=> refactor zero123

threestudio/models/renderers/nerf_volume_renderer.py, threestudio/models/renderers/neus_volume_renderer.py, threestudio/utils/ops.py
Validate empty rays based on the number of elements. If `ray_indices` is empty, use the first ray and set its start and end to zero. This validation avoids errors and will not influence the training process when rays are empty.
Before:
After:
=> Validate empty rays

threestudio/systems/zero123.py, threestudio/utils/saving.py
Minor fix in saving noise_levels for wandb. Doesn't affect anything other than guidance_eval, which is only used in zero123 so far.
Fixes issue of saving noise level with guidance_eval image : earlier, the image was saved, read, noise level was printed on it, then the image was saved again. Now the noise level is first printed on image, then image is saved.
=> Fixes saving noise-levels in guidance_eval

threestudio/models/guidance/zero123_guidance.py
Bugfix in guidance_eval, fixes conditioning to zero123 during guidance-eval
BEFORE:
AFTER:
=> Fix guidance_eval

CHANGELOG.md, DOCUMENTATION.md, threestudio/models/renderers/__init__.py, threestudio/models/renderers/patch_renderer.py
Support the general patch-based renderer. The ```patch_renderer``` can significantly reduce memory usage during high-resolution training. The ```patch_renderer```  first renders a full low-resolution downsampled image and then randomly renders a local patch at the original resolution level. The ```patch_renderer``` can be combined with any existing renderer to reduce their memory usage. Here is an explanation of its configuration:
- patch_size: the size of the local patch.
- global_downsample: downsample scale of the original rendering size.
- global_detach: option to detach or not detach the gradient of the downsampled image.
- base_renderer_type and base_renderer: configurations of any existing renderer.
Here is an example:
```
renderer_type: "patch-renderer"
renderer: …
```
=> Patch-based renderer

threestudio/models/renderers/neus_volume_renderer.py
Support utilization of volsdf density function in neus volume renderer. I have discovered that VolSDF is more stable than NeuS in sparse multi-view reconstruction tasks and 3D generation using VSD loss. VolSDF is less prone to generating artifacts and less likely to collapse.
=> Support volsdf density function in neus volume renderer

configs/experimental/imagecondition.yaml, threestudio/models/guidance/deep_floyd_guidance.py, threestudio/models/guidance/stable_diffusion_guidance.py, threestudio/models/guidance/stable_diffusion_vsd_guidance.py, threestudio/models/guidance/zero123_guidance.py, threestudio/systems/base.py, threestudio/systems/imagedreamfusion.py, threestudio/systems/zero123.py
1. Accumulates grad in imagedreamfusion
Fixes imagedreamfusion to accumulate grads from ref and guidance
2. Adds guidance_eval to stable_diffusion, deep_floyd
Adds the ability to optionally evaluate guidance periodically, in stable_diffusion and deep_floyd (as done in zero123)
This does not affect current working of stable_diffusion, deep_floyd, it only adds the option to visualize the guidance.
I used the following command to check the results with stable diffusion guidance:
`python launch.py --config configs/experimental/imagecondition.yaml --train --gpu 0 system.freq.ref_only_steps=20 system.freq.guidance_eval=13`
To run with deep floyd guidance, I uncommented the requisite lines in `configs/experimental/imagecondition.yaml`.
First, since `ref_only_steps=20`, it should run with just …
=> ImageDreamfusion accumulate grad, guidance_eval in sd,if

threestudio/models/renderers/nerf_volume_renderer.py, threestudio/models/renderers/neus_volume_renderer.py, threestudio/utils/ops.py
Following the suggestion by @bennyguo,  fix bugs in Nerfacc caused by the validation of empty rays.
=> Fix bugs in Nerfacc caused by the validation of empty rays

threestudio/models/geometry/implicit_sdf.py, threestudio/models/geometry/implicit_volume.py, threestudio/models/geometry/volume_grid.py
Rename the original calculation of finite difference as ```finite_difference_laplacian```. The new algorithm for the finite difference is based on 3 points, resulting in reduced memory consumption and improved rendering speed.
In the dreamfusion experiments:
- finite_difference_laplacian, 5.0it/s, 9500MB
- finite_difference, 5.3it/s, 6800MB
- analytic, 5.3it/s, 5200MB
=> New algorithm for finite difference based on 3 points

threestudio/models/guidance/deep_floyd_guidance.py, threestudio/models/guidance/stable_diffusion_guidance.py, threestudio/models/guidance/zero123_guidance.py, threestudio/systems/base.py, threestudio/utils/saving.py
Prints noise_level, elevation, azimuth, cam_distance (instead of only noise_level)
BEFORE:
AFTER:
=> Guidance_eval: print noise_level, elevation, azimuth, cam_distance

configs/prolificdreamer-geometry.yaml, configs/prolificdreamer-patch.yaml, configs/prolificdreamer-scene.yaml, configs/prolificdreamer-texture.yaml, configs/prolificdreamer.yaml, threestudio/models/guidance/controlnet_guidance.py, threestudio/models/guidance/deep_floyd_guidance.py, threestudio/models/guidance/instructpix2pix_guidance.py, threestudio/models/guidance/stable_diffusion_guidance.py, threestudio/models/guidance/stable_diffusion_vsd_guidance.py, threestudio/models/guidance/zero123_guidance.py, threestudio/systems/zero123.py
This PR is related to #175 . I made the following changes:
- add `set_min_max_steps` to all guidance (as in #175)
- in the `update_step` hook of all guidance, use `C` to get the parsed value of `min_step` and `max_step` if they're specified by a tuple of four numbers
- add `min_step` and `max_step` to the return dict of the guidance, so that we could monitor the actual used value in tensorboard / wandb
=> Enable linearly changing min/max steps in guidance

README.md, configs/prolificdreamer-scene.yaml, configs/prolificdreamer.yaml
In the latest version, the batch_size should have the same length as the width/height.
=> Update batchsize in config/prolificdreamer.yaml

threestudio/models/mesh.py
When doing the unwrap_uv in the Mesh class, the vertices are not detached from the computation graph, which will make xatlas raise an error.
This error can happen for example when using fantasia3d second stage without fixing the geometry.
=> detach vertices before adding to xatlas

launch.py, threestudio/models/geometry/implicit_sdf.py, threestudio/utils/misc.py
- Set a different seed for each device. We don't need to worry about the model initialization as Lightning will automatically sync the params across ranks.
- Manually sync the model params after optimization-based initialization as I found Lightning won't sync in this case.
=> Fix Multi-GPU Seed Problem

.gitattributes, docs/installation.md, load/tets/256_tets.npz
Reverts threestudio-project/threestudio#224 due to Git LFS bandwidth limit
=> Revert "Enable git-lfs and add 256_tets.npz"

threestudio/models/geometry/implicit_volume.py, threestudio/models/geometry/volume_grid.py
I find a mistake in my ```finite_difference``` implementation for NeRF. The direction of normal should be reversed.
=> Correct the normal direction of finite_difference

threestudio/data/uncond.py
`torch.rand(self.cfg.batch_size) * math.pi - 2 * math.pi` results in [-2*pi, -pi). It should be corrected as `torch.rand(self.cfg.batch_size) * math.pi * 2 - math.pi`
=> Correct sampling of light azimuth

DOCUMENTATION.md, configs/fantasia3d-texture.yaml, threestudio/models/geometry/__init__.py, threestudio/models/geometry/custom_mesh.py, threestudio/models/geometry/implicit_sdf.py
Wrote a new module for training texture only.
=> Load fixed custom mesh and train texture only.

threestudio/models/prompt_processors/base.py
There should be an assertion to ensure the embedding process completes successfully
=> Assert the text embeddings process successfully runs

docker/Dockerfile
RIght now docker build fails with an error:
```
> [threestudio  6/10] RUN pip install git+https://github.com/KAIR-BAIR/nerfacc.git@v0.5.2:
0.340 Defaulting to user installation because normal site-packages is not writeable
0.362 Collecting git+https://github.com/KAIR-BAIR/nerfacc.git@v0.5.2
0.362   Cloning https://github.com/KAIR-BAIR/nerfacc.git (to revision v0.5.2) to /tmp/pip-req-build-l6bkrwqs
0.364   Running command git clone --filter=blob:none --quiet https://github.com/KAIR-BAIR/nerfacc.git /tmp/pip-req-build-l6bkrwqs
1.984   Running command git checkout -q d84cdf3afd7dcfc42150e0f0506db58a5ce62812
2.553   Resolved https://github.com/KAIR-BAIR/nerfacc.git to commit d84cdf3afd7dcfc42150e0f0506db58a5ce62812
2.554   Running command git submodule update --init --recursive -q
7.459 …
```
=> Lock setuptools version
